import os
from tkinter import *

root = Tk()
root.title("Arcadia")
w = Label(root, text='WELCOME TO ARCADIA', font = ('cooper black', '36'), fg = "dark blue")
w.pack()
w1 = Label(root, text='Your go to app for arcade games', font = ('monotype corsiva', '30'), fg = "black")
w1.pack()
frame = Frame(root)
frame.pack()
button1 = Button(frame, text = 'Pacman', fg ='orange', width = 14, font = ('calibri','24'), command = lambda: os.system('python run.py'))
button1.pack( side = TOP, pady = 5 )
button2 = Button(frame, text = 'Flappy Bird', fg='crimson',width = 14, font = ('calibri','24'), command = lambda: os.system('python flappy.py'))
button2.pack( side = TOP, pady = 5 )
button3 = Button(frame, text ='Tic Tac Toe', fg ='purple',width = 14, font = ('calibri','24'), command = lambda: os.system('python TicTacToe.py'))
button3.pack( side = TOP, pady = 5 )
button4 = Button(frame, text ='2048 Game', fg ='dark green',width = 14, font = ('calibri','24'), command = lambda: os.system('python 2048.py'))
button4.pack( side = TOP, pady = 5 )
button5 = Button(frame, text ='Snake Game', fg ='olive',width = 14, font = ('calibri','24'), command = lambda: os.system('python SnakeGame.py'))
button5.pack( side = TOP, pady = 5 )
button6 = Button(frame, text ='Quit', fg = 'brown', width = 14, font = ('calibri','24'), command = lambda: root.destroy())
button6.pack( side = TOP, pady = 5 )
root.mainloop()